all: studentOBD2 UserOBD2Terminal

studentOBD2: studentOBD2.c
	gcc studentOBD2.c -o studentOBD2
	chmod +x studentOBD2

UserOBD2Terminal: UserOBD2Terminal.c
	gcc UserOBD2Terminal.c -o UserOBD2Terminal
	chmod +x UserOBD2Terminal
