all: vehicule_checker_student dashboard road_follower

vehicule_checker_student: vehicule_checker_student.c
	gcc vehicule_checker_student.c -o vehicule_checker_student
	chmod +x vehicule_checker_student

dashboard: dashboard.c
	gcc dashboard.c -o dashboard
	chmod +x dashboard

road_follower: road_follower.c
	gcc road_follower.c -o road_follower
	chmod +x road_follower