all: vehicule_checker_student dashboard

vehicule_checker_student: vehicule_checker_student.c
	gcc vehicule_checker_student.c -o vehicule_checker_student
	chmod +x vehicule_checker_student

dashboard: dashboard.c
	gcc dashboard.c -o dashboard
	chmod +x dashboard