version: '3.7'

services:
  backend-purple:
    build: ./backend/simpleapi
    hostname: devops-backend-purple
    networks:
      - app-network
    depends_on:
      - database
  backend-yellow:
    build: ./backend/simpleapi
    hostname: devops-backend-yellow
    networks:
      - app-network
    depends_on:
      - database
  database:
    build: ./database
    hostname: devops-bdd
    networks:
      - app-network
  httpd:
    build: ./frontend
    ports:
      - 8080:80
    networks:
      - app-network
    depends_on:
      - backend-purple
      - backend-yellow

networks:
  app-network:
