name: Package
on:
  workflow_run:
    workflows: "CI devops 2023"
    types: [requested]
    branches:
      - master

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: devops/TP/backend/simpleapi
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/inge.courses-s8.devops.takima.bdd:backend
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: devops/TP/database
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/inge.courses-s8.devops.takima.bdd
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: devops/TP/frontend
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/inge.courses-s8.devops.takima.bdd:frontend
          push: ${{ github.ref == 'refs/heads/master' }}

